FROM node:14

WORKDIR /app

COPY package*.json ./

RUN npm install -g nodemon

RUN npm install
RUN npm install -g serve

COPY . .

# Build application (production build)
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
